### ISSUE TITLE
Some questions about simulated data

### ISSUE THREAD

**Issue by ChyLeeX** [lzygenomics/SONAR#1]
Hi, Zhiyuan! 
I am very interested in this work you are proposing. The experimental results in this work are rich, especially the simulation part of the experiment considers many different scenarios. However, I didn't find your code for generating simulated data, could you share your code with me? If possible, send it to my email chyli721@gmail.com!
Thanks a lot!

**Comment by lzygenomics** [comment]
Hi,@chyli721-ccnu !

Thank you for your interest in our work. We are glad to hear that you find our experimental results rich and comprehensive. We will upload the code for generating simulated data to Github as soon as possible and let you know. Please stay tuned for updates. Thank you for your patience and support!

Zhiyuan

**Comment by lzygenomics** [comment]
Hi @chyli721-ccnu !

We have uploaded the corresponding files in this GitHub named "Simulation code", please do not hesitate to contact us if you have any questions. 

Best,

Zhiyuan
