### ISSUE TITLE
CMP package

### ISSUE THREAD

**Issue by lauradmartens** [lzygenomics/SONAR#2]
Thanks a lot for providing your detailed code! I was trying to work with the simulation code and have a very difficult time finding the CMP package. Could you point me to how/where you installed it?

Thanks a lot!

**Comment by lzygenomics** [comment]
Hi @lauradmartens ~

Thank you for your interests! Here is the CMP's link: https://github.com/James-Thorson/Conway-Maxwell-Poisson Hope to help you : )

Best!

**Comment by lauradmartens** [comment]
Great! Thanks a lot for the super quick reply!
